export type TagType =
  | "tag-eng"
  | "tag-design"
  | "tag-mkt"
  | "tag-hr"
  | "tag-ops";

export interface Job {
  id: number;
  title: string;
  dept: string;
  tag: TagType;
  type: string;
  experience: string;
  location: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
}

export const jobs: Job[] = [
  {
    id: 1,
    title: "DevOps Engineer",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Full-Time",
    experience: "Junior / Mid-Level / Senior",
    location: "Hyderabad",
    description: `We are looking for a skilled DevOps Engineer to join our engineering team. The ideal candidate will be responsible for implementing and managing the infrastructure and automation tools that support our development and deployment pipelines. You will play a key role in enhancing the speed, security, and reliability of our applications.`,
    responsibilities: [
      "Design, implement, and maintain CI/CD pipelines for automated code integration and deployment.",
      "Manage cloud infrastructure (AWS, Azure, GCP) using Infrastructure as Code (IaC) tools like Terraform or CloudFormation.",
      "Monitor system performance and troubleshoot issues in development, test, and production environments.",
      "Improve system reliability, scalability, and security.",
      "Collaborate with developers, QA engineers, and IT staff to ensure seamless software delivery.",
      "Automate repetitive tasks and optimize the development workflow.",
      "Implement security best practices and compliance standards.",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Information Technology, or a related field.",
      "Good Hands on experience in a DevOps or related role.",
      "Hands-on experience with CI/CD tools (e.g., Jenkins, GitLab CI, GitHub Actions).",
      "Strong experience with cloud platforms like AWS, Azure, or GCP.",
      "Proficient in scripting languages such as Bash, Python, or PowerShell.",
      "Familiarity with containerization (Docker) and orchestration tools (Kubernetes, ECS, EKS).",
      "Experience with configuration management tools (e.g., Ansible, Chef, Puppet).",
      "Understanding of networking, security, and system administration fundamentals.",
      "Certification in AWS, Azure, or other cloud technologies.",
      "Experience with monitoring and logging tools (e.g., Prometheus, Grafana, ELK stack).",
      "Knowledge of Agile methodologies and DevSecOps practices.",
      "Experience with GitOps or service mesh technologies.",
    ],
  },
  {
    id: 2,
    title: "Full Stack Developer (React + Java)",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Full-Time",
    experience: "Junior / Mid-Level / Senior",
    location: "Hyderabad",
    description: `We are looking for a Full Stack Developer proficient in React (front-end) and Java (back-end) to join our development team. You will be responsible for building and maintaining end-to-end web applications, collaborating with cross-functional teams, and delivering high-quality software solutions that meet user and business needs.`,
    responsibilities: [
      "Design, develop, and maintain full stack web applications using React and Java (Spring Boot).",
      "Implement responsive and intuitive user interfaces using React and modern front-end technologies.",
      "Develop and consume RESTful APIs and microservices.",
      "Write clean, efficient, and well-documented code on both front-end and back-end.",
      "Collaborate with UX designers, product managers, and QA engineers.",
      "Troubleshoot issues, perform root cause analysis, and optimize performance.",
      "Ensure security, scalability, and maintainability of the application.",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Engineering, or a related field.",
      "Strong proficiency in Java, Spring Boot, and REST APIs.",
      "Good Hands-on experience with React.js, Redux (or other state management libraries), HTML5 & CSS3.",
      "Familiarity with front-end tools like Webpack, Babel, or Vite.",
      "Experience with databases (e.g., PostgreSQL, MySQL, MongoDB).",
      "Good understanding of Git, CI/CD pipelines, and Agile development practices.",
      "Knowledge of authentication (OAuth, JWT) and authorization best practices.",
      "Experience with containerization tools (Docker, Kubernetes).",
      "Familiarity with cloud platforms (AWS, Azure, GCP).",
      "Testing skills using tools like Jest, Mocha, JUnit, or Postman.",
    ],
  },
  {
    id: 3,
    title: "AI Engineer / AI Developer",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Full-Time",
    experience: "Junior / Mid-Level / Senior",
    location: "Hyderabad",
    description: `We are seeking talented and driven AI Engineers and Developers to join our team. In this role, you will design, develop, and deploy artificial intelligence and machine learning models and systems. You'll work closely with data scientists, product managers, and software engineers to build intelligent solutions that drive innovation and deliver real-world impact.`,
    responsibilities: [
      "Design and implement machine learning models and AI algorithms to solve real-world problems.",
      "Build and integrate AI-driven solutions into existing applications and workflows.",
      "Work with large datasets to pre-process, clean, and analyse data for modelling.",
      "Collaborate with cross-functional teams to define system requirements and AI capabilities.",
      "Optimize models for performance, accuracy, scalability, and deployment.",
      "Develop APIs and services to expose AI models in production environments.",
      "Monitor, evaluate, and iterate on deployed models and AI systems.",
      "Research emerging technologies and apply best practices in AI/ML.",
    ],
    requirements: [
      "Bachelor's or Master's degree in Computer Science, AI, Data Science, or related fields.",
      "Strong proficiency in Python and libraries like TensorFlow, PyTorch, Scikit-learn, or Keras.",
      "Hand-on Experience with machine learning algorithms (classification, regression, clustering, etc.).",
      "Familiarity with deep learning architectures (CNNs, RNNs, Transformers).",
      "Understanding of data structures, algorithms, and software design principles.",
      "Experience with data engineering tools (e.g., Pandas, NumPy) & cloud platforms (AWS, Azure, GCP).",
      "Knowledge of REST APIs and model deployment using tools like Flask, FastAPI, or Docker.",
      "Experience with NLP, computer vision, recommendation systems, or reinforcement learning.",
      "Hands-on experience with MLOps practices and model lifecycle management.",
      "Familiarity with tools like MLflow, Kubeflow, or SageMaker.",
      "Experience with databases and data pipelines (SQL, NoSQL, Airflow).",
      "Contributions to open-source AI/ML projects or research publications.",
    ],
  },
  {
    id: 4,
    title: "UI/UX Designer",
    dept: "Design",
    tag: "tag-design",
    type: "Full-Time",
    experience: "Junior / Mid-Level / Senior",
    location: "Hyderabad",
    description: `We are looking for a creative and detail-oriented UI/UX Designer to join our team. You will be responsible for designing intuitive, engaging, and user-centric digital experiences across our web and mobile platforms. You will collaborate closely with product managers, developers, and stakeholders to translate ideas into elegant and functional designs.`,
    responsibilities: [
      "Design user-friendly interfaces and seamless user experiences for web and mobile applications.",
      "Create wireframes, prototypes, and high-fidelity designs using tools like Figma, Sketch, or Adobe XD.",
      "Conduct user research, usability testing, and gather feedback to improve product design.",
      "Collaborate with product managers and developers to ensure design feasibility and implementation.",
      "Maintain and evolve design systems, style guides, and UI components.",
      "Ensure consistency in branding, layout, and visual identity across all products.",
      "Stay updated with the latest UI/UX trends, tools, and best practices.",
    ],
    requirements: [
      "Bachelor's degree in Design, Human-Computer Interaction (HCI), or related field.",
      "Good experience in UI/UX design for web or mobile applications.",
      "Proficiency in design tools such as Figma, Adobe XD, Sketch, or similar.",
      "Strong understanding of user-centered design principles and usability standards.",
      "Experience with prototyping, wireframing, and interaction design.",
      "Basic understanding of front-end technologies (HTML, CSS, JavaScript) is a plus.",
      "Strong communication and collaboration skills.",
      "Experience with design systems and component libraries.",
      "Knowledge of accessibility standards and responsive design.",
      "Familiarity with Agile/Scrum workflows.",
    ],
  },
  {
    id: 5,
    title: "Digital Marketing Executive",
    dept: "Marketing",
    tag: "tag-mkt",
    type: "Full-Time",
    experience: "Junior / Mid-Level / Senior",
    location: "Hyderabad",
    description:
      "We are looking for a creative and data-driven Digital Marketing Executive to join our team. In this role, you will be responsible for planning, executing, and optimizing digital campaigns across multiple channels. You will help grow brand awareness, drive user acquisition, and improve engagement for Stikbook.",
    responsibilities: [
      "Plan and execute digital marketing campaigns across platforms such as Google, Instagram, Facebook, and LinkedIn.",
      "Manage social media accounts and create engaging content including posts, reels, and campaigns.",
      "Run paid ads (Google Ads, Meta Ads) and optimize them for performance and ROI.",
      "Analyze campaign performance using tools like Google Analytics and provide actionable insights.",
      "Collaborate with design and product teams to create marketing creatives and landing pages.",
      "Implement SEO strategies to improve website ranking and organic traffic.",
      "Track user behavior and optimize funnels for better conversion rates.",
      "Stay updated with the latest digital marketing trends, tools, and best practices.",
    ],
    requirements: [
      "Bachelor's degree in Marketing, Business, or a related field.",
      "Experience in digital marketing, social media, or performance marketing.",
      "Hands-on experience with Google Ads, Meta Ads, and analytics tools.",
      "Strong understanding of SEO, SEM, and content marketing.",
      "Ability to analyze data and make data-driven decisions.",
      "Excellent communication and creative thinking skills.",
      "Experience with tools like Google Analytics, SEMrush, or HubSpot is a plus.",
      "Familiarity with basic design tools like Canva or Figma is a bonus.",
    ],
  },
  {
    id: 6,
    title: "DevOps Intern",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Internship",
    experience: "Intern / Fresher",
    location: "Remote / Onsite (Hyderabad)",
    description: `We are looking for a DevOps Intern to support our engineering team in automating and managing infrastructure and deployment processes. This is a great opportunity to gain hands-on experience with cloud and DevOps tools.`,
    responsibilities: [
      "Assist in maintaining CI/CD pipelines and deployment workflows.",
      "Support cloud infrastructure setup and monitoring.",
      "Help automate repetitive tasks and improve workflows.",
      "Collaborate with developers and QA teams.",
      "Learn DevOps tools and best practices.",
    ],
    requirements: [
      "Currently pursuing or recently completed a degree in Computer Science or IT.",
      "Basic understanding of DevOps concepts and cloud platforms.",
      "Familiarity with Git and scripting (Bash or Python) is a plus.",
      "Strong willingness to learn new tools and technologies.",
    ],
  },
  {
    id: 7,
    title: "Full Stack Developer Intern (React + Java)",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Internship",
    experience: "Intern / Fresher",
    location: "Remote / Onsite (Hyderabad)",
    description: `We are looking for a Full Stack Developer Intern to work on both front-end and back-end technologies. You will gain hands-on experience building modern web applications using React and Java.`,
    responsibilities: [
      "Assist in developing front-end interfaces using React.",
      "Support back-end development using Java and Spring Boot.",
      "Work on REST APIs and integration tasks.",
      "Debug and fix issues across the stack.",
      "Collaborate with designers and developers.",
    ],
    requirements: [
      "Basic knowledge of Java and JavaScript.",
      "Familiarity with React or front-end frameworks.",
      "Understanding of APIs and databases.",
      "Strong willingness to learn full stack development.",
    ],
  },
  {
    id: 8,
    title: "AI / ML Intern",
    dept: "Engineering",
    tag: "tag-eng",
    type: "Internship",
    experience: "Intern / Fresher",
    location: "Remote / Onsite (Hyderabad)",
    description: `We are looking for an AI/ML Intern to assist in developing machine learning models and intelligent systems. This role offers hands-on exposure to real-world AI applications.`,
    responsibilities: [
      "Assist in building and training machine learning models.",
      "Work with datasets for cleaning and preprocessing.",
      "Support model evaluation and optimization.",
      "Collaborate with engineers and data scientists.",
      "Research and experiment with new AI techniques.",
    ],
    requirements: [
      "Basic knowledge of Python and machine learning concepts.",
      "Familiarity with libraries like TensorFlow, PyTorch, or Scikit-learn.",
      "Understanding of data structures and algorithms.",
      "Strong analytical and problem-solving skills.",
    ],
  },
  {
    id: 9,
    title: "UI/UX Designer Intern",
    dept: "Design",
    tag: "tag-design",
    type: "Internship",
    experience: "Intern / Fresher",
    location: "Remote / Onsite (Hyderabad)",
    description: `We are looking for a UI/UX Designer Intern to assist in creating user-friendly and visually appealing designs for our digital products. This is a great opportunity to build a strong design portfolio.`,
    responsibilities: [
      "Assist in designing user interfaces for web and mobile applications.",
      "Create wireframes, prototypes, and design mockups.",
      "Support user research and usability testing.",
      "Collaborate with developers and product teams.",
      "Maintain design consistency and follow design systems.",
    ],
    requirements: [
      "Basic knowledge of UI/UX design principles.",
      "Familiarity with tools like Figma, Adobe XD, or Sketch.",
      "Creative thinking and attention to detail.",
      "Strong willingness to learn and improve design skills.",
    ],
  },
  {
    id: 10,
    title: "Digital Marketing Intern",
    dept: "Marketing",
    tag: "tag-mkt",
    type: "Internship",
    experience: "Intern / Fresher",
    location: "Remote / Onsite (Hyderabad)",
    description:
      "We are looking for a creative and enthusiastic Digital Marketing Intern to join our team. This role is perfect for someone eager to learn and gain hands-on experience in social media, content creation, and performance marketing.",
    responsibilities: [
      "Assist in planning and executing digital marketing campaigns across social media platforms.",
      "Create engaging content including posts, captions, and short-form videos (reels).",
      "Support in managing social media accounts and responding to user interactions.",
      "Help run and monitor paid ad campaigns (Meta Ads, Google Ads).",
      "Conduct basic market and competitor research.",
      "Track campaign performance and prepare simple reports.",
      "Assist with SEO activities such as keyword research and content optimization.",
      "Collaborate with design and product teams for marketing creatives.",
    ],
    requirements: [
      "Currently pursuing or recently completed a degree in Marketing, Business, or a related field.",
      "Basic understanding of social media platforms and digital marketing concepts.",
      "Interest in content creation, trends, and online marketing.",
      "Good communication and creative thinking skills.",
      "Familiarity with tools like Canva, Instagram, or Google Analytics is a plus.",
      "Willingness to learn and adapt in a fast-paced environment.",
    ],
  },
];

export const tagColorMap: Record<TagType, string> = {
  "tag-eng": "#297c3b",
  "tag-design": "#1d4ed8",
  "tag-mkt": "#b45309",
  "tag-hr": "#6b21a8",
  "tag-ops": "#9f1239",
};
